# Config file for automatic testing at travis-ci.org

language: python

env:
    - PY=''
    - PY=3

install:
  - sudo pip install nose
  - sudo pip install numpy
  - sudo pip install scipy

script:
  - python$PY setup.py install --user

  - python$PY run_tests.py

  - cd documentation/sphinx
  - make html
