# Config file for automatic testing at travis-ci.org

language: python

env:
    - PY=''
    - PY=3

install:
  # Deactivate the virtualenv to get fast install of dependencies
  - deactivate
  # add ppa with more recent scipy version
  - echo 'yes' | sudo add-apt-repository ppa:pylab/stable 
  - sudo apt-get update
  - sudo apt-get install -qq python$PY-sphinx python$PY-nose python$PY-numpy python$PY-scipy

script:
  - python$PY setup.py install --user
  - python$PY run_tests.py
  - cd documentation/sphinx
  - make html