# Config file for automatic testing at travis-ci.org

language: python

env:
    - PY=''
    - PY=3

install:
  # Deactivate the virtualenv to get fast install of dependencies
  - deactivate
  - sudo apt-get install -qq python$PY-sphinx python$PY-nose
  - sudo apt-get install -qq python$PY-numpy
  - sudo apt-get install -qq python$PY-scipy

script:
  - python$PY setup.py install --user

  - python$PY run_tests.py

  - cd documentation/sphinx
  - make html
