# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.6
  - 3.3

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  - pip install nose
  - pip install numpy
  - pip install Cython
  # mpmath for scipy.special tests
  - pip install mpmath
  # For Python 2.6 we also need argparse
  - pip install argparse
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - python -V
  - popd

install:
  - sudo pip install nose
  - sudo pip install numpy
  - sudo pip install scipy

script:
  - python$PY setup.py install --user
  - python$PY run_tests.py
  - cd documentation/sphinx
  - make html
